pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: 'sudo apt update; sudo apt -y install gcc-arm-linux-gnueabi'
- script: 'curl http://www.airspayce.com/mikem/bcm2835/bcm2835-1.58.tar.gz | tar zxf -'
  displayName: 'download and extract bcm2835'
  
- script: 'cd bcm2835* && arm-linux-gnueabi-gcc -shared -o libbcm2835.so -fPIC src/bcm2835.c && gzip -3 libbcm2835.so'
  displayName: 'make and compress shared library'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'releases token'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    tag: 'v-pipeline-$(Build.SourceVersion)'
    target: '$(Build.SourceVersion)'
    assets: 'bcm2835*/libbcm2835.so.gz'
